name: Version Bump Helper

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Bump version
        run: npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
      
      - name: Get new version
        id: version
        run: echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          title: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          body: |
            ## Version Bump: ${{ steps.version.outputs.new_version }}
            
            Please update CHANGELOG.md with the changes for this version before merging.
            
            ### Checklist
            - [ ] Update CHANGELOG.md with new version section
            - [ ] Add all changes under appropriate categories (Added/Changed/Fixed/etc.)
            - [ ] Update date in CHANGELOG.md
            - [ ] Review package.json version
          branch: version-bump-${{ steps.version.outputs.new_version }}
